apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-persona
  namespace: name2
  labels:
    app: api-persona
    version: v1
spec:
  selector:
    matchLabels:
      app: api-persona
      version: v1
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template: 
    metadata:
      labels:
        app: api-persona
        version: v1
    spec:
      containers:
        - name: api-persona 
          image: juanmendieta21/api-persona
          imagePullPolicy: Always
          ports:
              - containerPort: 8080
          env:
          - name: host
            valueFrom:
              configMapKeyRef:
                name: configmap-app
                key: hostbd
          - name: port
            valueFrom:
              secretKeyRef:
                name: secrets-app
                key: portbd
          - name: database
            valueFrom:
              secretKeyRef:
                name: secrets-app
                key: database
          - name: password
            valueFrom:
              secretKeyRef:
                name: secrets-app
                key: pwdbd
          - name: username
            valueFrom:
              secretKeyRef:
                name: secrets-app
                key: userbd
          - name: MYSQL_ROOT_HOST
            valueFrom:
              secretKeyRef:
                name: secrets-app
                key: roothost
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "500Mi"
              cpu: "1"