apiVersion: v1
kind: Service
metadata:
  name: svc-loadbalancer
  namespace: name2
spec:
  type: LoadBalancer
  selector:
    app: api-persona
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: listener-1