apiVersion: v1
kind: Pod
metadata:
  name: database
  namespace: name1
  annotations:
    sample: 800-555-1212
  labels:
    app: database
    version: v1
spec:
  containers:
   - name: bd   
     image: juanmendieta21/database
     ports:
        - containerPort: 3306
  restartPolicy: OnFailure 
