apiVersion: v1
kind: Service
metadata:
  name: my-cips-api-persona
  namespace: name1
spec:
  type: ClusterIP
  selector:
    app: api-persona
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080