apiVersion: v1
kind: Pod
metadata:
  name: stack-api-persona
  annotations:
    sample: 800-555-1212
  labels:
    app: api-persona
    version: v1
spec:
  containers:
   - name: api-persona 
     image: juanmendieta21/api-persona
     ports:
        - containerPort: 8080
     env:
        - name: host
          value: localhost
        - name: port
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: toor
        - name: MYSQL_ROOT_HOST
          value: "%"
   - name: bd   
     image: juanmendieta/database
     ports:
        - containerPort: 3306
  restartPolicy: OnFailure 
