apiVersion: v1
kind: Pod
metadata:
  name: cliente
  labels:
    app: nginx2
    project: frontend-enterprise
spec:
  containers:
   - name: nginx
     image: nginx:latest
     ports:
        - containerPort: 80
